Fix NoSuchMethodError for unit tests
With all the code movement, some tests were found to break. Update the
proguard config so the appropriate methods can be referenced.

bug 3460695

Change-Id: I2fc9786cc54182ba8571d87947241dcd7b2e9995